services:
  simple-apps:
    container_name: ct-simpleapps-prod-pipeline2
    build: ./app
    image: ketupats772/img-simpleapps:v1-stable
    ports:
    - "10002:3000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
